### ISSUE TITLE
Remove Chicago-specific information from repo

### ISSUE THREAD

**Issue by AcademyInPeril** [vkoves/Transit-Network#27]
Continuing in our aim to make this repository into a generic platform from which location-specific apps are forked, we should remove all information and code that is related specifically to the Chicago Transit Authority (CTA) or other Chicago-based transit systems.

**Comment by morrme** [comment]
Like this page? 
https://github.com/vkoves/Transit-Network/blob/master/app/views/pages/about.html.erb

**Comment by AcademyInPeril** [comment]
@morrme, yes, that's one example. I just fixed a number of items related to this issue in 6bcfd42acf781cb4f64fda3bb5b9cf31201cdd52. We still have to re-orient our introductory documents somewhat, as well, so this issue is remaining open.

**Comment by AcademyInPeril** [comment]
Solved remaining localization issues with 5e6e967eb47b9bf3dc9586da29a027881c943cbb
