### ISSUE TITLE
Track Transit Vehicles Live

### ISSUE THREAD

**Issue by grant-rez** [vkoves/Transit-Network#7]
This is the last step for implementing real-time transit tracking. This is useful for end users as it allows them to plan their time around where the transit is at any time. This goal is important to work towards because it increases the amount of use the framework will get as it will allow users to gather more information from it. [Here](http://mbus.doublemap.com/map/) is an example of a website that integrates google maps well. The Transit-Network's goal is to cover as many uses as possible, so it is important to keep all implementations broad and usable in as many locations as possible.

**Comment by AcademyInPeril** [comment]
Now that Transit Network has a mildly different focus than in its original form, this will be a project to tackle in forked apps, not in the platform repo.
